In [97]:
import numpy as np
import pandas as pd

from sklearn.tree import DecisionTreeClassifier 
# from sklearn.tree import DecisionTreeRegressor
from sklearn.tree import plot_tree

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV

import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

In [76]:
data=pd.read_csv('penguins[1].csv')
data.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  year  
0       3750.0    male  2007  
1       3800.0  female  2007  
2       3250.0  female  2007  
3          NaN     NaN  2007  
4       3450.0  female  2007

In [77]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            344 non-null    object 
 1   island             344 non-null    object 
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object 
 7   year               344 non-null    int64  
dtypes: float64(4), int64(1), object(3)
memory usage: 21.6+ KB


In [78]:
data.describe()

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
count      342.000000     342.000000         342.000000   342.000000   
mean        43.921930      17.151170         200.915205  4201.754386   
std          5.459584       1.974793          14.061714   801.954536   
min         32.100000      13.100000         172.000000  2700.000000   
25%         39.225000      15.600000         190.000000  3550.000000   
50%         44.450000      17.300000         197.000000  4050.000000   
75%         48.500000      18.700000         213.000000  4750.000000   
max         59.600000      21.500000         231.000000  6300.000000   

              year  
count   344.000000  
mean   2008.029070  
std       0.818356  
min    2007.000000  
25%    2007.000000  
50%    2008.000000  
75%    2009.000000  
max    2009.000000

In [79]:
data['species'].unique()

array(['Adelie', 'Gentoo', 'Chinstrap'], dtype=object)

In [80]:
data['island'].unique()

array(['Torgersen', 'Biscoe', 'Dream'], dtype=object)

In [81]:
data['sex'].unique()

array(['male', 'female', nan], dtype=object)

In [82]:
data.loc[data['species'] == 'Adelie', 'species'] = 0
data.loc[data['species'] == 'Gentoo', 'species'] = 1
data.loc[data['species'] == 'Chinstrap', 'species'] = 2


In [83]:
data

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0         0  Torgersen            39.1           18.7              181.0   
1         0  Torgersen            39.5           17.4              186.0   
2         0  Torgersen            40.3           18.0              195.0   
3         0  Torgersen             NaN            NaN                NaN   
4         0  Torgersen            36.7           19.3              193.0   
..      ...        ...             ...            ...                ...   
339       2      Dream            55.8           19.8              207.0   
340       2      Dream            43.5           18.1              202.0   
341       2      Dream            49.6           18.2              193.0   
342       2      Dream            50.8           19.0              210.0   
343       2      Dream            50.2           18.7              198.0   

     body_mass_g     sex  year  
0         3750.0    male  2007  
1         3800.0  female  2007  
2         3250.0  female  2007  
3            NaN     NaN  2007  
4         3450.0  female  2007  
..           ...     ...   ...  
339       4000.0    male  2009  
340       3400.0  female  2009  
341       3775.0    male  2009  
342       4100.0    male  2009  
343       3775.0  female  2009  

[344 rows x 8 columns]

In [84]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
data['island'] = label_encoder.fit_transform(data['island'])


In [85]:
data

species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0         0       2            39.1           18.7              181.0   
1         0       2            39.5           17.4              186.0   
2         0       2            40.3           18.0              195.0   
3         0       2             NaN            NaN                NaN   
4         0       2            36.7           19.3              193.0   
..      ...     ...             ...            ...                ...   
339       2       1            55.8           19.8              207.0   
340       2       1            43.5           18.1              202.0   
341       2       1            49.6           18.2              193.0   
342       2       1            50.8           19.0              210.0   
343       2       1            50.2           18.7              198.0   

     body_mass_g     sex  year  
0         3750.0    male  2007  
1         3800.0  female  2007  
2         3250.0  female  2007  
3            NaN     NaN  2007  
4         3450.0  female  2007  
..           ...     ...   ...  
339       4000.0    male  2009  
340       3400.0  female  2009  
341       3775.0    male  2009  
342       4100.0    male  2009  
343       3775.0  female  2009  

[344 rows x 8 columns]

In [86]:
data.isna().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
year                  0
dtype: int64

In [102]:
data['bill_length_mm']=data['bill_length_mm'].fillna(data['bill_length_mm'].median())
data['bill_depth_mm']=data['bill_depth_mm'].fillna(data['bill_depth_mm'].median())
data['flipper_length_mm']=data['flipper_length_mm'].fillna(data['flipper_length_mm'].median())
data['body_mass_g']=data['body_mass_g'].fillna(data['body_mass_g'].median())
# data['flipper_length_mm']=data['flipper_length_mm'].fillna(data['flipper_length_mm'].median)

### filling  nall point to median of each in features 

In [103]:
data

species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0         0       2           39.10           18.7              181.0   
1         0       2           39.50           17.4              186.0   
2         0       2           40.30           18.0              195.0   
3         0       2           44.45           17.3              197.0   
4         0       2           36.70           19.3              193.0   
..      ...     ...             ...            ...                ...   
339       2       1           55.80           19.8              207.0   
340       2       1           43.50           18.1              202.0   
341       2       1           49.60           18.2              193.0   
342       2       1           50.80           19.0              210.0   
343       2       1           50.20           18.7              198.0   

     body_mass_g  sex  year  
0         3750.0  1.0  2007  
1         3800.0  0.0  2007  
2         3250.0  0.0  2007  
3         4050.0  1.0  2007  
4         3450.0  0.0  2007  
..           ...  ...   ...  
339       4000.0  1.0  2009  
340       3400.0  0.0  2009  
341       3775.0  1.0  2009  
342       4100.0  1.0  2009  
343       3775.0  0.0  2009  

[344 rows x 8 columns]

In [104]:
data.loc[data['sex'] == 'female', 'sex'] = 0
data.loc[data['sex'] == 'male', 'sex'] = 1

In [105]:
data['sex']=data['sex'].fillna(data['sex'].median())

In [120]:
data


species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0          0       2           39.10           18.7              181.0   
1          0       2           39.50           17.4              186.0   
2          0       2           40.30           18.0              195.0   
3          0       2           44.45           17.3              197.0   
4          0       2           36.70           19.3              193.0   
..       ...     ...             ...            ...                ...   
339        2       1           55.80           19.8              207.0   
340        2       1           43.50           18.1              202.0   
341        2       1           49.60           18.2              193.0   
342        2       1           50.80           19.0              210.0   
343        2       1           50.20           18.7              198.0   

     body_mass_g  sex  year  
0         3750.0  1.0  2007  
1         3800.0  0.0  2007  
2         3250.0  0.0  2007  
3         4050.0  1.0  2007  
4         3450.0  0.0  2007  
..           ...  ...   ...  
339       4000.0  1.0  2009  
340       3400.0  0.0  2009  
341       3775.0  1.0  2009  
342       4100.0  1.0  2009  
343       3775.0  0.0  2009  

[344 rows x 8 columns]

In [145]:
X=data.iloc[:,1:]
X

island  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
0         2           39.10           18.7              181.0       3750.0
1         2           39.50           17.4              186.0       3800.0
2         2           40.30           18.0              195.0       3250.0
3         2           44.45           17.3              197.0       4050.0
4         2           36.70           19.3              193.0       3450.0
..      ...             ...            ...                ...          ...
339       1           55.80           19.8              207.0       4000.0
340       1           43.50           18.1              202.0       3400.0
341       1           49.60           18.2              193.0       3775.0
342       1           50.80           19.0              210.0       4100.0
343       1           50.20           18.7              198.0       3775.0

[344 rows x 5 columns]

In [158]:
y=data.species
y

0      0
1      0
2      0
3      0
4      0
      ..
339    2
340    2
341    2
342    2
343    2
Name: species, Length: 344, dtype: int32

In [159]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25,
                                                    random_state=42)

In [160]:
X_test

island  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
194       0            45.3           13.7              210.0       4300.0
157       0            46.5           13.5              210.0       4550.0
225       0            46.5           14.8              217.0       5200.0
208       0            43.8           13.9              208.0       4300.0
318       1            50.9           19.1              196.0       3550.0
..      ...             ...            ...                ...          ...
332       1            45.2           16.6              191.0       3250.0
239       0            51.3           14.2              218.0       5300.0
132       1            36.8           18.5              193.0       3500.0
202       0            46.6           14.2              210.0       4850.0
152       0            46.1           13.2              211.0       4500.0

[86 rows x 5 columns]

In [161]:
data.isna().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
year                 0
dtype: int64

In [162]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            344 non-null    int32  
 1   island             344 non-null    int32  
 2   bill_length_mm     344 non-null    float64
 3   bill_depth_mm      344 non-null    float64
 4   flipper_length_mm  344 non-null    float64
 5   body_mass_g        344 non-null    float64
 6   sex                344 non-null    float64
 7   year               344 non-null    int64  
dtypes: float64(5), int32(2), int64(1)
memory usage: 18.9 KB


In [163]:
data


species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0          0       2           39.10           18.7              181.0   
1          0       2           39.50           17.4              186.0   
2          0       2           40.30           18.0              195.0   
3          0       2           44.45           17.3              197.0   
4          0       2           36.70           19.3              193.0   
..       ...     ...             ...            ...                ...   
339        2       1           55.80           19.8              207.0   
340        2       1           43.50           18.1              202.0   
341        2       1           49.60           18.2              193.0   
342        2       1           50.80           19.0              210.0   
343        2       1           50.20           18.7              198.0   

     body_mass_g  sex  year  
0         3750.0  1.0  2007  
1         3800.0  0.0  2007  
2         3250.0  0.0  2007  
3         4050.0  1.0  2007  
4         3450.0  0.0  2007  
..           ...  ...   ...  
339       4000.0  1.0  2009  
340       3400.0  0.0  2009  
341       3775.0  1.0  2009  
342       4100.0  1.0  2009  
343       3775.0  0.0  2009  

[344 rows x 8 columns]

In [164]:
data['species']=data['species'].astype(int)

In [165]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            344 non-null    int32  
 1   island             344 non-null    int32  
 2   bill_length_mm     344 non-null    float64
 3   bill_depth_mm      344 non-null    float64
 4   flipper_length_mm  344 non-null    float64
 5   body_mass_g        344 non-null    float64
 6   sex                344 non-null    float64
 7   year               344 non-null    int64  
dtypes: float64(5), int32(2), int64(1)
memory usage: 18.9 KB


In [166]:
dt_model = DecisionTreeClassifier(criterion='gini')
dt_model.fit(X_train, y_train)

DecisionTreeClassifier()

In [167]:
y_pred_test = dt_model.predict(X_test)
test_accuracy = accuracy_score(y_test, y_pred_test)
print("Testing accuracy is :", test_accuracy)
# clf_report = classification_report(y_test, y_pred_test)
# print("Classification report is\n", clf_report)
# print()

conf_matrix = confusion_matrix(y_test, y_pred_test)
print("Confusion matrix\n", conf_matrix)

Testing accuracy is : 0.9767441860465116
Confusion matrix
 [[38  0  2]
 [ 0 29  0]
 [ 0  0 17]]


In [156]:
dt_model.predict([[1,50,18,198.0,775]])

array([2])

In [170]:
print(classification_report(y_test, y_pred_test))

              precision    recall  f1-score   support

           0       1.00      0.95      0.97        40
           1       1.00      1.00      1.00        29
           2       0.89      1.00      0.94        17

    accuracy                           0.98        86
   macro avg       0.96      0.98      0.97        86
weighted avg       0.98      0.98      0.98        86



In [174]:
plt.figure(figsize=(200,100))
tree = plot_tree(decision_tree=dt_model, feature_names=X.columns,
                class_names=['0', '1','2'], filled=True)
plt.show("DT_diabetes.png")